version: '3'
services:
  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend/:/usr/src/app/
    # command: sh -c 'cd teab && yarn start'
    ports:
      - 7000:7000
    tty: true
